gmt-china/gmt-china.org

content/blog/2016-11-07-gdal-ogr.md

fix OGR of blog 2016-11-07-gdal-ogr.md

---

content/datas/_index.md

add following lines for index.md of datas directory
CN-block-L1.dat (/datas/CN-block-L1.dat): 中国大陆一级地块边界数据
CN-block-L1-deduced.dat (/datas/CN-block-L1-deduced.dat): 中国大陆一级地块推断边界数据
CN-block-L2.dat (/datas/CN-block-L2.dat): 中国大陆二级地块边界数据

add download link of block data 

---

layouts/_default/baseof.html
layouts/_default/section.html
layouts/_default/single.html
layouts/partials/article_footer.html
layouts/partials/gitalk.html

创建了 gitalk 库用来存储 社区评论，目前只修改 gmt-china.org 用来检验实际效果

修改了 layout/_default/baseof.html 用于添加 gitalk 评论软件

---

content/docs/_index.md

fix faq typo

---

content/example/ex003/CN-border-JD.sh
content/example/ex003/CN-border-JM.sh

modernize to 6

---

content/home/download.md

更改日志在 https://docs.generic-mapping-tools.org/6.1/changes.html#new-features-in-gmt-6-1

更新GMT版本到6.1.0

---

content/home/download.md

update the newest link of gmt6.1.1

update link of gmt6.1.1

---

content/example/ex026/legendLB.txt
content/example/ex026/plot_subduction.GMT6.bat

gmt6.bat for ex026

---

content/example/ex026/plot_subduction.GMT6.bat

change coding for gmt6.bat of ex026

Fix encoding of ex026 batch script

---

.github/workflows/check-links.yml

Add a workflow to check links

---

content/blog/2020-02-19-vscode-usage/index.md

GBK应该也是可以的。但中文手册和视频教程里都是说改为GB2312，因此这里也统一为GB2312

GBK改为GB2312

---

.github/workflows/preview-pr.yml

Add PR preview

---

.github/workflows/preview-pr.yml

This PR fixes some issues with the preview-pr workflow. 
Now the preview works, although some figures are not displayed correctly.
Closes #180.

Fix the preview workflow

---

content/example/ex002/index.md
layouts/partials/head_custom.html

https://gmt-china.org/example/ex002/ will be redirected to https://docs.gmt-china.org/latest/examples/ex002/ in **0** seconds.
The time interval can be changed to other values.
Please give it a try.

Redirect ex002 to docs.gmt-china.org

---

content/home/download.md

Bump to GMT 6.2.0

---

content/home/download.md

Update to gs9540

---

content/home/contact.md

Closes https://github.com/gmt-china/GMT_docs/issues/600

Add link to community guide

---

content/home/download.md

update to gs9550

---

content/home/contact.md

Update contact information

---

content/blog/2017-08-17-instructions-for-authors/index.md

Address https://github.com/gmt-china/gmt-china.org/issues/155#issuecomment-1128627436.
Closes https://github.com/gmt-china/gmt-china.org/issues/155.

Update instructions for authors

---

content/home/download.md

Add instructions to download old releases

---

content/home/contact.md

Closes https://github.com/gmt-china/gmt-china.org/issues/211.

Add the link to maintainers
